INSERT INTO DEPARTEMENT (NOM) VALUES ('Comptabilite');
INSERT INTO DEPARTEMENT (NOM) VALUES ('Ressource Humaine');
INSERT INTO DEPARTEMENT (NOM) VALUES ('Informatiques');

INSERT INTO BANQUE (NOM_BANQUE,IBAN,BIC) VALUES ('SOCIETE GENERAlE','2536565F','45PP');
INSERT INTO BANQUE (NOM_BANQUE,IBAN,BIC) VALUES ('LA POSTE','MP87878','666');
INSERT INTO BANQUE (NOM_BANQUE,IBAN,BIC) VALUES ('CREDIT AGRICOLE','98985545P','POUR');

INSERT INTO COLLABORATEUR (ACTIF,ADRESSE,DATE_DE_NAISSANCE,EMAIL_PRO,MATRICULE,NOM,NUMERO_SECURITE_SOCIAL,PRENOM,DEPARTEMENT_ID,BANQUE_ID) VALUES ('true','8 rue de la roche','1991-06-03','emai@pro.com','M01','Maxime','45158794','Duchene','1','1');
INSERT INTO COLLABORATEUR (ACTIF,ADRESSE,DATE_DE_NAISSANCE,EMAIL_PRO,MATRICULE,NOM,NUMERO_SECURITE_SOCIAL,PRENOM,DEPARTEMENT_ID,BANQUE_ID) VALUES ('true','La vallée de Danna','1990-06-05','emai@pro.com','M02','Duchene','875451','Maxine','2','2');
INSERT INTO COLLABORATEUR (ACTIF,ADRESSE,DATE_DE_NAISSANCE,EMAIL_PRO,MATRICULE,NOM,NUMERO_SECURITE_SOCIAL,PRENOM,DEPARTEMENT_ID,BANQUE_ID) VALUES ('true','Etampes','1918-05-08','emai@pro.com','M03','Denver','666','le dernier Dinosaure','3','3');
